ctl: upload junit files and ansible.log after a run
Change-Id: If4519984e865ef73028539045cf8da6dcf9c3038

diff --git a/dci-openshift-agent-ctl b/dci-openshift-agent-ctl
--- a/dci-openshift-agent-ctl
+++ b/dci-openshift-agent-ctl
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+ANSIBLE_PID=
+JOB_ID_FILE=
+OUTPUT_DIR=
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 start=0
 params="$(getopt -o hsdp:c:v -l help,start,dev,prefix:,config:,verbose --name "$(basename -- "$0")" -- "$@")"
@@ -23,6 +26,40 @@ arguments:
 EOF
     exit $1
 }
+
+function finish ()
+{
+    echo "finish $*"
+
+    if [ -n "${ANSIBLE_PID}" ]; then
+        PGID=$(ps -o pgid= ${ANSIBLE_PID} | grep -o [0-9]*)
+
+        if [ -n "${ANSIBLE_PID}" ]; then
+            kill -KILL -$PGID
+        else
+            echo "Unable to find process group for ${ANSIBLE_PID}"
+            kill ${ANSIBLE_PID}
+        fi
+
+        wait ${ANSIBLE_PID}
+        exit $?
+    fi
+
+    if [ -n "${JOB_ID_FILE}" -a -n "${OUTPUT_DIR}" ]; then
+        JOB_ID=$(cat ${JOB_ID_FILE})
+        for junit_file in $(ls ${OUTPUT_DIR}/*.xml); do
+            junit_filename=$(basename ${junit_file} .xml)
+            dcictl job-upload-file --name ${junit_filename} --path ${junit_file} --mime application/junit ${JOB_ID}
+        done
+        if [ -r ${OUTPUT_DIR}/ansible.log ]; then
+            dcictl job-upload-file --name ansible.log --path ${OUTPUT_DIR}/ansible.log ${JOB_ID}
+        fi
+        echo "removing output dir: ${OUTPUT_DIR}"
+        rm -rf ${OUTPUT_DIR}
+    fi
+}
+
+trap finish 0
 
 if [ -r /etc/dci-openshift-agent/config ]; then
     . /etc/dci-openshift-agent/config
@@ -97,12 +134,28 @@ fi
 if [ "$start" -eq 1 ]; then
     if [ -z "$dev" ]; then
         [ -e /etc/dci-openshift-agent/dcirc.sh ] && . /etc/dci-openshift-agent/dcirc.sh
-        [ -d ${DCI_OPENSHIFT_AGENT_DIR:-/usr/share/dci-openshift-agent} ] && cd ${DCI_OPENSHIFT_AGENT_DIR:-/usr/share/dci-openshift-agent}
+        DCI_OPENSHIFT_AGENT_DIR=${DCI_OPENSHIFT_AGENT_DIR:-/usr/share/dci-openshift-agent}
+        export ANSIBLE_CONFIG=${ANSIBLE_CONFIG:-$DCI_OPENSHIFT_AGENT_DIR/ansible.cfg}
     else
         [ -e $DIR/dcirc.sh ] && . $DIR/dcirc.sh
         export ANSIBLE_CONFIG=$DIR/dev-ansible.cfg
+        DCI_OPENSHIFT_AGENT_DIR=${DCI_OPENSHIFT_AGENT_DIR:-$DIR}
     fi
-    exec ansible-playbook dci-openshift-agent.yml -e @$config ${prefix_args} "$@"
+
+    OUTPUT_DIR="$(mktemp -d /tmp/dci-openshift-agent.XXXXX)"
+    cd ${OUTPUT_DIR}
+    JOB_ID_FILE="$OUTPUT_DIR/dci-openshift-agent.job"
+    export ANSIBLE_LOG_PATH=${OUTPUT_DIR}/ansible.log
+    export JUNIT_OUTPUT_DIR=${OUTPUT_DIR}
+    export JUNIT_TEST_CASE_PREFIX=test_
+    export JUNIT_TASK_CLASS=yes
+    cat ${ANSIBLE_CONFIG}
+    setsid ansible-playbook -v ${DCI_OPENSHIFT_AGENT_DIR}/dci-openshift-agent.yml -e JOB_ID_FILE="${JOB_ID_FILE}" -e @$config ${prefix_args} "$@" &
+    ANSIBLE_PID=$!
+
+    wait ${ANSIBLE_PID}
+    ANSIBLE_PID=
+    exit $?
 else
     echo "Dry-Run: pass -s or --start to actually execute"
     if [ -z "$dev" ]; then
@@ -112,6 +165,11 @@ else
         echo "$DIR/dcirc.sh"
         echo "ANSIBLE_CONFIG=$DIR/dev-ansible.cfg"
     fi
-    echo ansible-playbook dci-openshift-agent.yml -e @$config ${prefix_args} "$@"
+    if [ -z "${OUTPUT_DIR}" ]; then
+        echo "setsid ansible-playbook dci-openshift-agent.yml -e @$config ${prefix_args} "$@" &"
+    else
+        JOB_ID_FILE="$(mktemp /tmp/job.XXXXX)"
+        echo "setsid ansible-playbook dci-openshift-agent.yml -e JOB_ID_FILE="${JOB_ID_FILE}" -e @$config ${prefix_args} "$@" &"
+    fi
     exit 1
 fi
