dci-check-change: improve kubeconfig support
- abort if kubeconfig is invalid
- do not launch through dci-queue if a kubeconfig is passed
- create a pipeline-id tag
- cleanup hack to run d-o-a-a as a different user

Change-Id: I1b82502f96d94db078a2471dbceb7b1aa384d0a3

diff --git a/dci-check-change b/dci-check-change
--- a/dci-check-change
+++ b/dci-check-change
@@ -26,6 +26,7 @@ VIRT=
 DCI_QUEUE=
 SNO_DCI_QUEUE=
 SUPPORTED_HINTS=
+NO_DCI_QUEUE=
 
 if [ -r /etc/dci-openshift-agent/config ]; then
     . /etc/dci-openshift-agent/config
@@ -36,14 +37,14 @@ BASEDIR=$(cd $(dirname $0); pwd)
 if [ $# = 0 ] || [ "$1" = -h ]; then
   name=$(basename -- "$0")
     cat << EOF
-    echo "Usage: $name [--virt|--sno] [-s] [-f] (<GitHub PR URL>|<Gerrit review id>) [<kubeconfig path>] [<ctl args>]" 1>&2
+    echo "Usage: $name [--virt|--sno] [-f] [-s] (<GitHub PR URL>|<Gerrit review id>) [<kubeconfig path>] [<ctl args>]" 1>&2
     Extract changes from Gerrit or GitHub and test them without impacting what is on the system.
 
     arguments:
     --virt            Use OCP on Libvirt.
     --sno             Use SNO on Libvirt.
-    -s                Force a suffix to be added.
     -f                Force to run without obeying hints.
+    -s                Force a suffix to be added.
     <kubeconfig path> To avoid running an OCP installation.
     <ctl args>        Arguments passed to the ctl.
 EOF
@@ -69,6 +70,12 @@ elif [ $1 = --sno ]; then
     shift
 fi
 
+# disable hints
+if [ "$1" = "-f" ]; then
+    SUPPORTED_HINTS=
+    shift
+fi
+
 # force a suffix to be added on -s
 if [ "$1" = "-s" ]; then
     # manage recursive call (bootstrap): extract the directory name
@@ -88,9 +95,13 @@ else
     shift
 fi
 
-# disable hints
-if [ "$1" = "-f" ]; then
-    SUPPORTED_HINTS=
+# validate kubeconfig or stop
+if [[ "$1" =~ .*/kubeconfig ]]; then
+    if ! oc --kubeconfig "$1" version || ! oc --kubeconfig "$1" get nodes; then
+        echo "Unable to use $1 to connect to OCP" 1>&2
+        exit 1
+    fi
+    NO_DCI_QUEUE=1
 fi
 
 case $CHANGEID in
