Add support for prefix
Make it easy to provision different clusters by using a prefix to
specify them.  --prefix=cluster1 will use
/etc/dci-openshift-agent/cluster1-hosts and
/etc/dci-openshift-agent/cluster1-settings.yml if present.

Prefix specific settings will override
/etc/dci-openshift-agent/settings.yml

Change-Id: I10d198fa63821ea0adee860ab52f58b8130218a7

diff --git a/dci-openshift-agent-ctl b/dci-openshift-agent-ctl
--- a/dci-openshift-agent-ctl
+++ b/dci-openshift-agent-ctl
@@ -2,17 +2,20 @@
 
 start=0
 config=/etc/dci-openshift-agent/settings.yml
-params="$(getopt -o hsc: -l help,start,config: --name "$(basename -- "$0")" -- "$@")"
+params="$(getopt -o hsp:c: -l help,start,prefix:,config: --name "$(basename -- "$0")" -- "$@")"
 
 function usage ()
 {
     name=$(basename -- "$0")
     cat << EOF
-Usage: $name [-h] [-s] [-c CONFIG] -- [ansible-playbook args]
+Usage: $name [-h] [-s] [-p PREFIX] [-c CONFIG] -- [ansible-playbook args]
 
 arguments:
     -h, --help        Display this help message.
     -s, --start       Start the dci-openshift-agent.
+    -p PREFIX, --prefix PREFIX
+                      Specify prefix for Inventory and settings (use to specify different
+                      clusters for example)
      -c CONFIG, --config CONFIG
                       Path to config file. default is /etc/dci-openshift-agent/settings.yml
 EOF
@@ -37,6 +40,11 @@ do
             config=$1
             shift
             ;;
+        -p|--prefix)
+            shift
+            prefix=$1
+            shift
+            ;;
         --)
             shift
             ansible_args=$@
@@ -53,10 +61,26 @@ if [ $( id -u dci-openshift-agent ) -ne $( id -u ) ]; then
   usage
 fi
 
+if [ -n "$prefix" ]; then
+    hosts="/etc/dci-openshift-agent/${prefix}-hosts"
+    settings="/etc/dci-openshift-agent/${prefix}-settings.yml"
+    if [ -e "$hosts" ]; then
+       prefix_args="-i $hosts"
+    else
+       echo "Missing $hosts"
+       exit 1
+    fi
+    if [ -e "$settings" ]; then
+        prefix_args="${prefix_args} -e @$settings"
+    else
+       echo "Missing $settings, will only use $config."
+    fi
+fi
+
 if [ "$start" -eq 1 ]; then
     [ -e /etc/dci-openshift-agent/dcirc.sh ] && . /etc/dci-openshift-agent/dcirc.sh
     [ -d /usr/share/dci-openshift-agent ] && cd /usr/share/dci-openshift-agent
-    ansible-playbook dci-openshift-agent.yml -e @$config $ansible_args
+    ansible-playbook dci-openshift-agent.yml -e @$config ${prefix_args} $ansible_args
 else
     usage
 fi
